export interface StyleGuide {
  slug: string;
  title: string;
  category: string;
  description: string;
  readTime: string;
  date: string;
  tag: string;
  emoji: string;
  image?: string;
  affiliateProducts?: AffiliateProduct[];
}

export interface AffiliateProduct {
  name: string;
  brand: string;
  price: string;
  url: string;
  tag?: string;
  image?: string;
}

export const categories = [
  { slug: 'all', name: 'All Styles', icon: '✨' },
  { slug: 'workwear', name: 'Workwear', icon: '👔' },
  { slug: 'casual', name: 'Casual Chic', icon: '👗' },
  { slug: 'date-night', name: 'Date Night', icon: '💃' },
  { slug: 'seasonal', name: 'Seasonal', icon: '🌸' },
  { slug: 'body-type', name: 'Body Types', icon: '💖' },
  { slug: 'budget', name: 'On a Budget', icon: '💰' },
  { slug: 'occasion', name: 'Occasions', icon: '🎉' },
];

export const guides: StyleGuide[] = [
  {
    slug: 'coastal-grandmother-style-guide-how-to-wear-the-viral-trend-that-lives-in-my-head-rentfree',
    title: 'Coastal Grandmother Style Guide: How to Wear the Editor\'s Choice Trend That Lives in My Head Rent-Free',
    category: 'Style Guide',
    description: 'Your ultimate coastal grandmother style guide with outfit ideas, styling tips, and shop-the-look essentials. Learn how to wear this Editor\'s Choice style like a pro.',
    readTime: '10 min',
    date: '2026-02-20',
    tag: 'Viral',
    emoji: '🐚',
    image: '/images/guides/coastal-grandmother-style-guide.svg',
    affiliateProducts: [],
  },

  {
    slug: 'refined-90s-minimalism-understated-luxury-curated-essentials',
    title: 'The Whisper of Luxury: Reclaiming Refined \'90s Minimalism for Today',
    category: 'casual',
    description: 'Explore the enduring allure of 90s minimalist fashion, a cultural shift towards understated refinement and elevated essentials in contemporary luxury.',
    readTime: '12 min',
    date: '2026-02-20',
    tag: 'Editor Pick',
    emoji: '🤍',
    image: '/images/guides/refined-90s-minimalism-understated-luxury.svg',
    affiliateProducts: [
      { name: 'Slim-cut tailored trousers in wool crepe', brand: 'Amazon', price: 'See Price', url: 'https://www.amazon.com/s?k=Slim-cut+tailored+trousers+in+wool+crepe&tag=styleme-20', tag: 'Editor Pick', image: '/images/products/slim-cut-tailored-trousers-in-wool-crepe.webp' },
      { name: 'Bias-cut silk slip dress', brand: 'Amazon', price: 'See Price', url: 'https://www.amazon.com/s?k=Bias-cut+silk+slip+dress&tag=styleme-20', image: '/images/products/bias-cut-silk-slip-dress.webp' },
      { name: 'Oversized single-breasted blazer', brand: 'Amazon', price: 'See Price', url: 'https://www.amazon.com/s?k=Oversized+single-breasted+blazer&tag=styleme-20', image: '/images/products/oversized-single-breasted-blazer.webp' },
      { name: 'Cashmere crewneck sweater', brand: 'Amazon', price: 'See Price', url: 'https://www.amazon.com/s?k=Cashmere+crewneck+sweater&tag=styleme-20', image: '/images/products/cashmere-crewneck-sweater.webp' },
      { name: 'Elongated column skirt', brand: 'Amazon', price: 'See Price', url: 'https://www.amazon.com/s?k=Elongated+column+skirt&tag=styleme-20', image: '/images/products/elongated-column-skirt.webp' },
    ],
  },

  {
    slug: 'coquette-aesthetic-guide-feminine-style-2026',
    title: 'Coquette Aesthetic: The Ultimate Guide to Feminine Dressing in 2026',
    category: 'casual',
    description: 'Master the coquette aesthetic with bows, lace, ballet flats, and soft pastels. Your complete guide to the ultra-feminine Editor\'s Choice style with outfit ideas and affordable picks.',
    readTime: '10 min',
    date: '2026-02-19',
    tag: 'Hot',
    emoji: '🎀',
    image: '/images/guides/coquette-aesthetic-feminine-style-2026.svg',
    affiliateProducts: [
      { name: 'Satin Bow Hair Clips Set', brand: 'Amazon', price: '$12', url: 'https://amzn.to/4rVjOFg', tag: 'Editor Pick', image: '/images/products/satin-bow-hair-clips-set.webp' },
      { name: 'Lace Trim Camisole Top', brand: 'Amazon', price: '$22', url: 'https://amzn.to/3ZCaw4S', image: '/images/products/lace-trim-camisole-top.webp' },
      { name: 'Ballet Flats with Bow', brand: 'Amazon', price: '$35', url: 'https://amzn.to/3Mro3JB', image: '/images/products/ballet-flats-with-bow.webp' },
      { name: 'Pearl Drop Earrings', brand: 'Amazon', price: '$15', url: 'https://amzn.to/3OhrhzW', image: '/images/products/pearl-drop-earrings.webp' },
    ],
  },

  {
    slug: 'gorpcore-for-women-your-complete-style-guide',
    title: 'Gorpcore for Women: Your Complete Style Guide',
    category: 'Fashion Trends',
    description: 'Master the gorpcore trend with our complete style guide. Learn how to wear outdoor-inspired fashion with outfit ideas perfect for Gen Z and millennial women.',
    readTime: '10 min',
    date: '2026-02-19',
    tag: 'Trending',
    emoji: '🥾',
    image: '/images/guides/gorpcore-for-women-complete-style-guide.svg',
    affiliateProducts: [
      { name: 'Waterproof Hiking Boots', brand: 'Amazon', price: '$58', url: 'https://amzn.to/4rVjOFg', tag: 'Editor Pick', image: '/images/products/waterproof-hiking-boots.webp' },
      { name: 'Fleece Half-Zip Pullover', brand: 'Amazon', price: '$35', url: 'https://amzn.to/3ZCaw4S', image: '/images/products/fleece-half-zip-pullover.webp' },
      { name: 'Cargo Jogger Pants', brand: 'Amazon', price: '$32', url: 'https://amzn.to/3Mro3JB', image: '/images/products/cargo-jogger-pants.webp' },
    ],
  },

  {
    slug: 'cottagecore-spring-outfits-that-are-trending-everywhere',
    title: 'Cottagecore Spring Outfits: Editor\'s Choice for 2026',
    category: 'Spring Fashion',
    description: 'Master cottagecore spring outfits with these Editor\'s Choice styling tips. Get outfit ideas, learn how to wear florals, and shop essential pieces for the perfect dreamy aesthetic.',
    readTime: '10 min',
    date: '2026-02-19',
    tag: 'Hot',
    emoji: '🌸',
    image: '/images/guides/cottagecore-spring-outfits.svg',
    affiliateProducts: [
      { name: 'Floral Midi Wrap Dress', brand: 'Amazon', price: '$38', url: 'https://amzn.to/3OhrhzW', tag: 'Best Seller', image: '/images/products/floral-midi-wrap-dress.webp' },
      { name: 'Straw Sun Hat', brand: 'Amazon', price: '$18', url: 'https://amzn.to/40drBCf', image: '/images/products/straw-sun-hat.webp' },
      { name: 'Puff Sleeve Linen Blouse', brand: 'Amazon', price: '$26', url: 'https://amzn.to/3ZCaw4S', image: '/images/products/puff-sleeve-linen-blouse.webp' },
    ],
  },

  {
    slug: 'clean-girl-aesthetic-2026-the-effortless-style-guide-everyones-obsessing-over',
    title: 'Clean Girl Aesthetic 2026: The Effortless Style Guide Everyone\'s Obsessing Over',
    category: 'casual',
    description: 'Master the viral clean girl aesthetic 2026 with effortless outfit ideas and styling tips -- an Editor\'s Choice selection.',
    readTime: '10 min',
    date: '2026-02-19',
    tag: 'Hot',
    emoji: '✨',
    image: '/images/guides/clean-girl-aesthetic-2026.svg',
    affiliateProducts: [
      { name: 'Gold Hoop Earrings Set', brand: 'Amazon', price: '$15', url: 'https://amzn.to/4rVjOFg', tag: 'Trending', image: '/images/products/gold-hoop-earrings-set.webp' },
      { name: 'Slicked-Back Headband Set', brand: 'Amazon', price: '$12', url: 'https://amzn.to/3Mro3JB', image: '/images/products/slicked-back-headband-set.webp' },
      { name: 'Fitted Ribbed Tank Top 3-Pack', brand: 'Amazon', price: '$24', url: 'https://amzn.to/3OhrhzW', image: '/images/products/fitted-ribbed-tank-top-3-pack.webp' },
    ],
  },

  {
    slug: 'balletcore-essentials-how-to-master-this-viral-trend',
    title: 'Balletcore Essentials: How to Master This Viral Trend',
    category: 'casual',
    description: 'Master balletcore essentials & outfit ideas with our viral style guide. Shop the perfect pieces & get styling tips now.',
    readTime: '10 min',
    date: '2026-02-19',
    tag: 'Hot',
    emoji: '🩰',
    image: '/images/guides/balletcore-essentials-viral-trend.svg',
    affiliateProducts: [
      { name: 'Wrap Ballet Flats', brand: 'Amazon', price: '$32', url: 'https://amzn.to/3ZCaw4S', tag: 'Editor Pick', image: '/images/products/wrap-ballet-flats.webp' },
      { name: 'Mesh Overlay Midi Skirt', brand: 'Amazon', price: '$28', url: 'https://amzn.to/40drBCf', image: '/images/products/mesh-overlay-midi-skirt.webp' },
      { name: 'Cropped Wrap Cardigan', brand: 'Amazon', price: '$26', url: 'https://amzn.to/4kNVNxy', image: '/images/products/cropped-wrap-cardigan.webp' },
    ],
  },

  {
    slug: 'gorpcore-for-women-3-styling-tips-outfit-ideas-that-own-the-trend',
    title: 'Gorpcore for Women: 3 Editor\'s Choice Styling Tips & Outfit Ideas',
    category: 'casual',
    description: 'Master gorpcore outfit ideas with our style guide. Layer pieces, mix earth tones & elevate with gold accessories.',
    readTime: '10 min',
    date: '2026-02-19',
    tag: 'Hot',
    emoji: '🎒',
    image: '/images/guides/gorpcore-styling-tips-outfit-ideas.svg',
    affiliateProducts: [
      { name: 'Puffer Vest', brand: 'Amazon', price: '$42', url: 'https://amzn.to/4rVjOFg', tag: 'Trending', image: '/images/products/puffer-vest.webp' },
      { name: 'Trail Running Sneakers', brand: 'Amazon', price: '$55', url: 'https://amzn.to/3Mro3JB', image: '/images/products/trail-running-sneakers.webp' },
      { name: 'Nylon Belt Bag', brand: 'Amazon', price: '$19', url: 'https://amzn.to/3OhrhzW', image: '/images/products/nylon-belt-bag.webp' },
    ],
  },

  {
    slug: 'eclectic-grandpa-style-the-ultimate-gen-z-trend-guide',
    title: 'Eclectic Grandpa Style: The Ultimate Gen Z Trend Guide',
    category: 'casual',
    description: 'Master the eclectic grandpa style trend with oversized cardigans, vintage pieces, and earthy tones. A complete guide for Gen Z and Millennials.',
    readTime: '10 min',
    date: '2026-02-19',
    tag: 'Hot',
    emoji: '🎩',
    image: '/images/guides/eclectic-grandpa-style-gen-z-guide.svg',
    affiliateProducts: [
      { name: 'Oversized Knit Cardigan', brand: 'Amazon', price: '$38', url: 'https://amzn.to/3ZCaw4S', tag: 'Editor Pick', image: '/images/products/oversized-knit-cardigan.webp' },
      { name: 'Corduroy Wide-Leg Trousers', brand: 'Amazon', price: '$34', url: 'https://amzn.to/40drBCf', image: '/images/products/corduroy-wide-leg-trousers.svg' },
      { name: 'Argyle Sweater Vest', brand: 'Amazon', price: '$25', url: 'https://amzn.to/4kNVNxy', image: '/images/products/argyle-sweater-vest.svg' },
    ],
  },

  {
    slug: 'office-siren-the-seductive-workwear-trend-you-need-to-try',
    title: 'Office Siren: The Seductive Workwear Trend You Need to Try',
    category: 'workwear',
    description: 'A complete guide to the office siren trend — the seductive workwear aesthetic blending corporate polish with alluring confidence. Includes key pieces, 3 styled outfits, and budget tips.',
    readTime: '10 min',
    date: '2026-02-19',
    tag: 'Hot',
    emoji: '👓',
    image: '/images/guides/office-siren-workwear-trend.svg',
    affiliateProducts: [
      { name: 'Fitted Pencil Skirt', brand: 'Amazon', price: '$28', url: 'https://amzn.to/3OhrhzW', tag: 'Best Seller', image: '/images/products/fitted-pencil-skirt.webp' },
      { name: 'Sheer Button-Down Blouse', brand: 'Amazon', price: '$24', url: 'https://amzn.to/3ZCaw4S', image: '/images/products/sheer-button-down-blouse.svg' },
      { name: 'Pointed-Toe Kitten Heels', brand: 'Amazon', price: '$42', url: 'https://amzn.to/4rVjOFg', image: '/images/products/pointed-toe-kitten-heels.svg' },
    ],
  },

  {
    slug: 'indie-sleaze-is-back-heres-how-to-nail-it-in-2025',
    title: 'Indie Sleaze Is Back — Here\'s How to Nail It in 2025',
    category: 'casual',
    description: 'A complete guide to the indie sleaze revival trend — key pieces, 3 outfit formulas, and styling tips for nailing the chaotic, effortless cool-girl aesthetic in 2025.',
    readTime: '10 min',
    date: '2026-02-19',
    tag: 'Hot',
    emoji: '🖤',
    image: '/images/guides/indie-sleaze-style-guide-2025.svg',
    affiliateProducts: [
      { name: 'Distressed Band Tee', brand: 'Amazon', price: '$22', url: 'https://amzn.to/3Mro3JB', tag: 'Trending', image: '/images/products/distressed-band-tee.svg' },
      { name: 'Faux Leather Mini Skirt', brand: 'Amazon', price: '$26', url: 'https://amzn.to/40drBCf', image: '/images/products/faux-leather-mini-skirt.svg' },
      { name: 'Chunky Platform Boots', brand: 'Amazon', price: '$52', url: 'https://amzn.to/4kNVNxy', image: '/images/products/chunky-platform-boots.svg' },
    ],
  },

  {
    slug: 'soft-girl-aesthetic-101-your-dreamy-style-guide',
    title: 'Soft Girl Aesthetic 101: Your Dreamy Style Guide 🎀☁️',
    category: 'casual',
    description: 'A complete guide to the soft girl aesthetic — key pastel pieces, 3 outfit formulas, styling tips, and budget-friendly shopping advice for a dreamy feminine wardrobe.',
    readTime: '10 min',
    date: '2026-02-19',
    tag: 'Hot',
    emoji: '🎀',
    image: '/images/guides/soft-girl-aesthetic-dreamy-style.svg',
    affiliateProducts: [
      { name: 'Pastel Cardigan with Pearl Buttons', brand: 'Amazon', price: '$30', url: 'https://amzn.to/3ZCaw4S', tag: 'Editor Pick', image: '/images/products/pastel-cardigan-with-pearl-buttons.webp' },
      { name: 'Pleated Tennis Skirt', brand: 'Amazon', price: '$22', url: 'https://amzn.to/3OhrhzW', image: '/images/products/pleated-tennis-skirt.svg' },
      { name: 'Cloud Slides Pastel Pink', brand: 'Amazon', price: '$18', url: 'https://amzn.to/4rVjOFg', image: '/images/products/cloud-slides-pastel-pink.svg' },
    ],
  },

  {
    slug: 'mob-wife-aesthetic-the-bold-luxe-trend-taking-over-2024',
    title: 'Mob Wife Aesthetic: The Bold, Luxe Trend Taking Over 2024',
    category: 'seasonal',
    description: 'Complete guide to the mob wife aesthetic — the bold, luxe 2024 trend featuring faux fur, gold jewelry, leopard print, and unapologetic glamour.',
    readTime: '10 min',
    date: '2026-02-19',
    tag: 'Hot',
    emoji: '🧥',
    image: '/images/guides/mob-wife-aesthetic-bold-luxe-trend.svg',
    affiliateProducts: [
      { name: 'Faux Fur Coat', brand: 'Amazon', price: '$65', url: 'https://amzn.to/4kNVNxy', tag: 'Editor Pick', image: '/images/products/faux-fur-coat.svg' },
      { name: 'Chunky Gold Chain Necklace', brand: 'Amazon', price: '$18', url: 'https://amzn.to/3Mro3JB', image: '/images/products/chunky-gold-chain-necklace.svg' },
      { name: 'Leopard Print Scarf', brand: 'Amazon', price: '$16', url: 'https://amzn.to/40drBCf', image: '/images/products/leopard-print-scarf.svg' },
    ],
  },

  {
    slug: 'maximalist-vintage-revival-how-to-master-the-moreismore-trend',
    title: 'Maximalist Vintage Revival: How to Master the More-Is-More Trend',
    category: 'casual',
    description: 'A complete guide to the maximalist vintage revival trend — how to mix eras, layer fearlessly, and build bold outfits with key vintage pieces.',
    readTime: '10 min',
    date: '2026-02-19',
    tag: 'Hot',
    emoji: '🌹',
    image: '/images/guides/maximalist-vintage-revival.svg',
    affiliateProducts: [
      { name: 'Vintage Patchwork Jacket', brand: 'Amazon', price: '$48', url: 'https://amzn.to/3ZCaw4S', tag: 'Trending', image: '/images/products/vintage-patchwork-jacket.svg' },
      { name: 'Printed Maxi Skirt', brand: 'Amazon', price: '$34', url: 'https://amzn.to/3OhrhzW', image: '/images/products/printed-maxi-skirt.svg' },
      { name: 'Chunky Statement Rings Set', brand: 'Amazon', price: '$15', url: 'https://amzn.to/4rVjOFg', image: '/images/products/chunky-statement-rings-set.svg' },
    ],
  },


  {
    slug: 'capsule-wardrobe-working-women-2026',
    title: 'The Ultimate Capsule Wardrobe Guide for Working Women 2026',
    category: 'workwear',
    description: 'Build a 30-piece wardrobe that creates 100+ outfits. From boardroom to brunch, this minimalist guide saves you time, money, and closet space.',
    readTime: '14 min',
    date: '2026-02-17',
    tag: 'Pillar Guide',
    emoji: '👔',
    image: '/images/guides/capsule-wardrobe-working-women-2026.svg',
    affiliateProducts: [
      { name: 'Tailored Blazer', brand: 'Amazon', price: '$49', url: 'https://amzn.to/4rVjOFg', tag: 'Editor Pick', image: '/images/products/tailored-blazer.svg' },
      { name: 'High-Rise Wide Leg Pants', brand: 'Amazon', price: '$38', url: 'https://amzn.to/3ZCaw4S', image: '/images/products/high-rise-wide-leg-pants.svg' },
      { name: 'Silk Camisole', brand: 'Amazon', price: '$25', url: 'https://amzn.to/3Mro3JB', image: '/images/products/silk-camisole.svg' },
      { name: 'Classic Pumps', brand: 'Amazon', price: '$45', url: 'https://amzn.to/3OhrhzW', image: '/images/products/classic-pumps.svg' },
    ],
  },
  {
    slug: 'casual-outfits-look-expensive',
    title: '15 Effortless Casual Outfits That Look Expensive on a Budget',
    category: 'casual',
    description: 'You don\'t need designer labels to look put-together. These 15 outfit formulas use affordable basics to create an elevated everyday look.',
    readTime: '10 min',
    date: '2026-02-15',
    tag: 'Trending',
    emoji: '👗',
    image: '/images/guides/casual-outfits-that-look-expensive.svg',
    affiliateProducts: [
      { name: 'Oversized Linen Shirt', brand: 'Amazon', price: '$28', url: 'https://amzn.to/4rVjOFg', tag: 'Best Value', image: '/images/products/oversized-linen-shirt.svg' },
      { name: 'Straight Leg Jeans', brand: 'Amazon', price: '$39', url: 'https://amzn.to/4rfVnSQ', image: '/images/products/straight-leg-jeans.svg' },
      { name: 'White Sneakers', brand: 'Amazon', price: '$45', url: 'https://amzn.to/3Mro7cj', image: '/images/products/white-sneakers.svg' },
    ],
  },
  {
    slug: 'first-date-outfits-every-vibe',
    title: 'What to Wear on a First Date: 20 Outfits for Every Vibe',
    category: 'date-night',
    description: 'Coffee date? Rooftop dinner? Hiking adventure? We\'ve got the perfect outfit for every type of first date, from low-key to dressed up.',
    readTime: '12 min',
    date: '2026-02-14',
    tag: 'Popular',
    emoji: '💃',
    image: '/images/guides/first-date-outfits-every-vibe.svg',
    affiliateProducts: [
      { name: 'Satin Midi Dress', brand: 'Amazon', price: '$42', url: 'https://amzn.to/4tH7kT9', tag: 'Date Night Fave', image: '/images/products/satin-midi-dress.svg' },
      { name: 'Strappy Heels', brand: 'Amazon', price: '$45', url: 'https://amzn.to/3OhrhzW', image: '/images/products/strappy-heels.svg' },
      { name: 'Statement Earrings', brand: 'Amazon', price: '$15', url: 'https://amzn.to/3Mro3JB', image: '/images/products/statement-earrings.svg' },
    ],
  },
  {
    slug: 'dress-for-body-shape-guide',
    title: 'Dressing for Your Body Shape: A Complete Visual Guide',
    category: 'body-type',
    description: 'Pear, apple, hourglass, rectangle, or inverted triangle? Find your body type and discover the cuts, fabrics, and silhouettes that flatter you most.',
    readTime: '16 min',
    date: '2026-02-12',
    tag: 'Evergreen',
    emoji: '💖',
    image: '/images/guides/dressing-for-body-shape-guide.svg',
    affiliateProducts: [
      { name: 'Wrap Dress (Hourglass)', brand: 'Amazon', price: '$36', url: 'https://amzn.to/4tH7kT9', image: '/images/products/wrap-dress-hourglass.svg' },
      { name: 'A-Line Skirt (Pear)', brand: 'Amazon', price: '$28', url: 'https://amzn.to/3ZCaw4S', image: '/images/products/a-line-skirt-pear.svg' },
      { name: 'Structured Blazer (Rectangle)', brand: 'Amazon', price: '$49', url: 'https://amzn.to/4rVjOFg', image: '/images/products/structured-blazer-rectangle.svg' },
    ],
  },
  {
    slug: 'nordstrom-vs-asos-professional-women',
    title: 'Nordstrom vs ASOS: Best Online Shopping for Professional Women',
    category: 'workwear',
    description: 'We compared both retailers on quality, price, sizing, returns, and style range. Here\'s which one is better for building your work wardrobe.',
    readTime: '11 min',
    date: '2026-02-08',
    tag: 'Comparison',
    emoji: '🛍️',
    image: '/images/guides/nordstrom-vs-asos-professional-women.svg',
    affiliateProducts: [
      { name: 'Work Blazer', brand: 'Amazon', price: '$49', url: 'https://amzn.to/4rVjOFg', tag: 'Top Pick', image: '/images/products/work-blazer.svg' },
      { name: 'Work Tote Bag', brand: 'Amazon', price: '$35', url: 'https://amzn.to/4anggFT', image: '/images/products/work-tote-bag.svg' },
    ],
  },
  {
    slug: 'what-to-wear-to-wedding-2026',
    title: 'What to Wear to a Wedding in 2026: Guest Outfit Guide',
    category: 'occasion',
    description: 'Black tie, garden party, beach ceremony, or city hall? The complete wedding guest outfit guide with do\'s, don\'ts, and shoppable looks.',
    readTime: '13 min',
    date: '2026-02-06',
    tag: 'Seasonal',
    emoji: '🎉',
    image: '/images/guides/wedding-guest-outfit-2026.svg',
    affiliateProducts: [
      { name: 'Wedding Guest Dress', brand: 'Amazon', price: '$42', url: 'https://amzn.to/4tH7kT9', tag: 'Best Seller', image: '/images/products/wedding-guest-dress.svg' },
      { name: 'Elegant Heels', brand: 'Amazon', price: '$45', url: 'https://amzn.to/3OhrhzW', image: '/images/products/elegant-heels.svg' },
    ],
  },
  {
    slug: 'best-jeans-for-women-2026',
    title: 'The 10 Best Jeans for Women in 2026 (Tested & Reviewed)',
    category: 'casual',
    description: 'We tried 40+ pairs across every body type and budget. These are the 10 that actually deliver on fit, comfort, and style.',
    readTime: '15 min',
    date: '2026-02-04',
    tag: 'Product Review',
    emoji: '👖',
    image: '/images/guides/best-jeans-for-women-2026.svg',
    affiliateProducts: [
      { name: 'Straight Leg Jeans', brand: 'Amazon', price: '$39', url: 'https://amzn.to/4rfVnSQ', tag: 'Best Overall', image: '/images/products/straight-leg-jeans.svg' },
      { name: 'Wide Leg Pants', brand: 'Amazon', price: '$38', url: 'https://amzn.to/3ZCaw4S', tag: 'Best Comfort', image: '/images/products/wide-leg-pants.svg' },
    ],
  },
  {
    slug: 'spring-workwear-capsule-2026',
    title: 'Spring 2026 Workwear Capsule: 15 Pieces, 30 Outfits',
    category: 'workwear',
    description: 'Build a complete spring work wardrobe with just 15 versatile pieces.',
    readTime: '12 min',
    date: '2026-03-01',
    tag: 'New',
    emoji: '🌸',
    image: '/images/guides/spring-workwear-capsule-2026.svg',
    affiliateProducts: [
      { name: 'Linen Blazer', brand: 'Amazon', price: '$49', url: 'https://amzn.to/4rVjOFg', tag: 'Editor Pick', image: '/images/products/linen-blazer.svg' },
      { name: 'Wide Leg Pants', brand: 'Amazon', price: '$38', url: 'https://amzn.to/3ZCaw4S', image: '/images/products/wide-leg-pants.svg' },
      { name: 'Silk Blouse', brand: 'Amazon', price: '$25', url: 'https://amzn.to/3Mro3JB', image: '/images/products/silk-blouse.svg' },
    ],
  },
  {
    slug: 'work-outfits-that-mean-business',
    title: '10 Work Outfits That Mean Business: Office Style Guide 2026',
    category: 'workwear',
    description: 'From power blazers to smart casual Friday — 10 effortlessly chic work outfits for the modern professional woman.',
    readTime: '14 min',
    date: '2026-02-17',
    tag: 'New',
    emoji: '💼',
    image: '/images/guides/work-outfits-that-mean-business.svg',
    affiliateProducts: [
      { name: 'Oversized Wool Blazer', brand: 'Amazon', price: '$49', url: 'https://amzn.to/4rVjOFg', tag: 'Editor Pick', image: '/images/products/oversized-wool-blazer.svg' },
      { name: 'High-Waisted Trousers', brand: 'Amazon', price: '$38', url: 'https://amzn.to/3ZCaw4S', tag: 'Best Value', image: '/images/products/high-waisted-trousers.svg' },
      { name: 'Silk Button-Down Shirt', brand: 'Amazon', price: '$25', url: 'https://amzn.to/3Mro3JB', image: '/images/products/silk-button-down-shirt.svg' },
      { name: 'Pointed Toe Pumps', brand: 'Amazon', price: '$45', url: 'https://amzn.to/3OhrhzW', image: '/images/products/pointed-toe-pumps.svg' },
    ],
  },
  {
    slug: 'what-to-wear-date-night',
    title: 'What to Wear on a Date Night: 7 Stunning Looks for Every Occasion',
    category: 'date-night',
    description: 'From fancy dinner to casual coffee — 7 gorgeous date night outfits that will make you feel confident and beautiful.',
    readTime: '11 min',
    date: '2026-02-17',
    tag: 'Trending',
    emoji: '💕',
    image: '/images/guides/what-to-wear-date-night.svg',
    affiliateProducts: [
      { name: 'Satin Midi Dress', brand: 'Amazon', price: '$42', url: 'https://amzn.to/4tH7kT9', tag: 'Editor Pick', image: '/images/products/satin-midi-dress.svg' },
      { name: 'Strappy Heeled Sandals', brand: 'Amazon', price: '$45', url: 'https://amzn.to/3OhrhzW', image: '/images/products/strappy-heeled-sandals.svg' },
      { name: 'Statement Earrings', brand: 'Amazon', price: '$15', url: 'https://amzn.to/3Mro3JB', tag: 'Budget Pick', image: '/images/products/statement-earrings.svg' },
      { name: 'Clutch Bag', brand: 'Amazon', price: '$22', url: 'https://amzn.to/4anggFT', image: '/images/products/clutch-bag.svg' },
    ],
  },
  {
    slug: 'best-jeans-every-body-type',
    title: 'Best Jeans for Every Body Type 2026: The Ultimate Denim Guide',
    category: 'casual',
    description: 'Find your perfect pair — the best jeans for pear, apple, hourglass, athletic, and petite body types.',
    readTime: '15 min',
    date: '2026-02-17',
    tag: 'Popular',
    emoji: '👖',
    image: '/images/guides/best-jeans-every-body-type.svg',
    affiliateProducts: [
      { name: 'Straight Leg Jeans', brand: 'Amazon', price: '$39', url: 'https://amzn.to/4rfVnSQ', tag: 'Best Overall', image: '/images/products/straight-leg-jeans.svg' },
      { name: 'Wide Leg Pants', brand: 'Amazon', price: '$38', url: 'https://amzn.to/3ZCaw4S', tag: 'Best for Curves', image: '/images/products/wide-leg-pants.svg' },
      { name: 'White Sneakers', brand: 'Amazon', price: '$45', url: 'https://amzn.to/3Mro7cj', tag: 'Best Pairing', image: '/images/products/white-sneakers.svg' },
    ],
  },
  {
    slug: 'spring-fashion-trends-2026',
    title: 'Spring Fashion Trends 2026: What to Wear This Season',
    category: 'seasonal',
    description: 'The biggest spring 2026 fashion trends and how to style them — from soft pastels to bold statement pieces.',
    readTime: '13 min',
    date: '2026-02-17',
    tag: 'Hot',
    emoji: '🌷',
    image: '/images/guides/spring-fashion-trends-2026.svg',
    affiliateProducts: [
      { name: 'Linen Blend Blazer', brand: 'Amazon', price: '$49', url: 'https://amzn.to/4rVjOFg', tag: 'Trend Pick', image: '/images/products/linen-blend-blazer.svg' },
      { name: 'Satin Midi Dress', brand: 'Amazon', price: '$42', url: 'https://amzn.to/4tH7kT9', image: '/images/products/satin-midi-dress.svg' },
      { name: 'Woven Tote Bag', brand: 'Amazon', price: '$35', url: 'https://amzn.to/4anggFT', tag: 'Must Have', image: '/images/products/woven-tote-bag.svg' },
      { name: 'White Sneakers', brand: 'Amazon', price: '$45', url: 'https://amzn.to/3Mro7cj', image: '/images/products/white-sneakers.svg' },
    ],
  },
  {
    slug: 'best-work-bags-under-100',
    title: 'The 10 Best Work Bags for Women Under $100 in 2026',
    category: 'workwear',
    description: 'Professional totes, structured satchels, and laptop-friendly bags that look expensive but won\'t break the bank.',
    readTime: '12 min',
    date: '2026-02-18',
    tag: 'Product Review',
    emoji: '👜',
    image: '/images/guides/best-work-bags-under-100.svg',
    affiliateProducts: [
      { name: 'Professional Tote Bag', brand: 'Amazon', price: '$35', url: 'https://amzn.to/4anggFT', tag: 'Best Overall', image: '/images/products/professional-tote-bag.svg' },
      { name: 'Structured Blazer', brand: 'Amazon', price: '$49', url: 'https://amzn.to/4rVjOFg', tag: 'Style It With', image: '/images/products/structured-blazer.svg' },
    ],
  },
  {
    slug: 'affordable-fashion-brands-guide',
    title: '12 Affordable Fashion Brands That Look High-End in 2026',
    category: 'budget',
    description: 'From H&M to Quince — these budget-friendly brands deliver quality, style, and sustainability without the designer price tag.',
    readTime: '11 min',
    date: '2026-02-18',
    tag: 'Budget',
    emoji: '💰',
    image: '/images/guides/affordable-fashion-brands-guide.svg',
    affiliateProducts: [
      { name: 'Silk Camisole', brand: 'Amazon', price: '$25', url: 'https://amzn.to/3Mro3JB', tag: 'Best Quality', image: '/images/products/silk-camisole.svg' },
      { name: 'Straight Leg Jeans', brand: 'Amazon', price: '$39', url: 'https://amzn.to/4rfVnSQ', image: '/images/products/straight-leg-jeans.svg' },
      { name: 'Tailored Blazer', brand: 'Amazon', price: '$49', url: 'https://amzn.to/4rVjOFg', tag: 'Editor Pick', image: '/images/products/tailored-blazer.svg' },
    ],
  },
  {
    slug: 'how-to-build-minimalist-wardrobe',
    title: 'How to Build a Minimalist Wardrobe: Step-by-Step Guide',
    category: 'casual',
    description: 'Declutter your closet and build a wardrobe that sparks joy. A practical guide to owning less but looking better every day.',
    readTime: '13 min',
    date: '2026-02-18',
    tag: 'Guide',
    emoji: '🪄',
    image: '/images/guides/how-to-build-minimalist-wardrobe.svg',
    affiliateProducts: [
      { name: 'Classic White Camisole', brand: 'Amazon', price: '$25', url: 'https://amzn.to/3Mro3JB', tag: 'Wardrobe Essential', image: '/images/products/classic-white-camisole.svg' },
      { name: 'Tailored Blazer', brand: 'Amazon', price: '$49', url: 'https://amzn.to/4rVjOFg', tag: 'Worth the Splurge', image: '/images/products/tailored-blazer.svg' },
      { name: 'Versatile Wide Leg Pants', brand: 'Amazon', price: '$38', url: 'https://amzn.to/3ZCaw4S', image: '/images/products/versatile-wide-leg-pants.svg' },
    ],
  },
  {
    slug: 'best-white-sneakers-women-2026',
    title: 'The 8 Best White Sneakers for Women in 2026 (Tested & Ranked)',
    category: 'casual',
    description: 'We tested 25+ pairs for comfort, durability, and style. These are the white sneakers that actually stay clean and look great with everything.',
    readTime: '14 min',
    date: '2026-02-18',
    tag: 'Product Review',
    emoji: '👟',
    image: '/images/guides/best-white-sneakers-women-2026.svg',
    affiliateProducts: [
      { name: 'White Sneakers', brand: 'Amazon', price: '$45', url: 'https://amzn.to/3Mro7cj', tag: 'Best Overall', image: '/images/products/white-sneakers.svg' },
      { name: 'Straight Leg Jeans', brand: 'Amazon', price: '$39', url: 'https://amzn.to/4rfVnSQ', tag: 'Best Pairing', image: '/images/products/straight-leg-jeans.svg' },
    ],
  },
  {
    slug: 'professional-outfits-women-2026',
    title: 'Professional Outfits for Women: Complete Office Wardrobe Guide',
    category: 'workwear',
    description: 'Whether your office is corporate, business casual, or creative — build a professional wardrobe that commands respect and looks amazing.',
    readTime: '15 min',
    date: '2026-02-18',
    tag: 'Comprehensive',
    emoji: '👩‍💼',
    image: '/images/guides/professional-outfits-women-2026.svg',
    affiliateProducts: [
      { name: 'Tailored Blazer', brand: 'Amazon', price: '$49', url: 'https://amzn.to/4rVjOFg', tag: 'Investment Piece', image: '/images/products/tailored-blazer.svg' },
      { name: 'Wide Leg Trousers', brand: 'Amazon', price: '$38', url: 'https://amzn.to/3ZCaw4S', tag: 'Best Value', image: '/images/products/wide-leg-trousers.svg' },
      { name: 'Silk Blouse', brand: 'Amazon', price: '$25', url: 'https://amzn.to/3Mro3JB', image: '/images/products/silk-blouse.svg' },
      { name: 'Pointed Toe Pumps', brand: 'Amazon', price: '$45', url: 'https://amzn.to/3OhrhzW', image: '/images/products/pointed-toe-pumps.svg' },
    ],
  },
  {
    slug: 'stitch-fix-vs-personal-stylist',
    title: 'Stitch Fix vs Hiring a Personal Stylist: Which is Right for You?',
    category: 'budget',
    description: 'We break down the cost, convenience, and styling quality of Stitch Fix versus traditional personal styling services.',
    readTime: '10 min',
    date: '2026-02-18',
    tag: 'Comparison',
    emoji: '🤔',
    image: '/images/guides/stitch-fix-vs-personal-stylist.svg',
    affiliateProducts: [
      { name: 'Build Your Own Style Kit', brand: 'Amazon', price: '$49', url: 'https://amzn.to/4rVjOFg', tag: 'DIY Pick', image: '/images/products/build-your-own-style-kit.svg' },
      { name: 'Work Tote Bag', brand: 'Amazon', price: '$35', url: 'https://amzn.to/4anggFT', image: '/images/products/work-tote-bag.svg' },
    ],
  },
  {
    slug: 'best-affordable-blazers-under-100',
    title: 'Best Affordable Blazers Under $100: 10 Picks for Every Style',
    category: 'budget',
    description: 'A great blazer transforms any outfit. These 10 affordable blazers deliver tailored quality and modern style without the premium price.',
    readTime: '12 min',
    date: '2026-02-18',
    tag: 'Product Review',
    emoji: '🧥',
    image: '/images/guides/best-affordable-blazers-under-100.svg',
    affiliateProducts: [
      { name: 'Classic Tailored Blazer', brand: 'Amazon', price: '$49', url: 'https://amzn.to/4rVjOFg', tag: 'Best Overall', image: '/images/products/classic-tailored-blazer.svg' },
      { name: 'Wide Leg Pants (Pair With)', brand: 'Amazon', price: '$38', url: 'https://amzn.to/3ZCaw4S', image: '/images/products/wide-leg-pants-pair-with.svg' },
      { name: 'Silk Camisole (Layer Under)', brand: 'Amazon', price: '$25', url: 'https://amzn.to/3Mro3JB', image: '/images/products/silk-camisole-layer-under.svg' },
    ],
  },
  {
    slug: 'what-to-wear-job-interview-2026',
    title: 'What to Wear to a Job Interview in 2026: Dress Code Guide',
    category: 'workwear',
    description: 'First impressions matter. The complete guide to interview outfits for corporate, startup, creative, and remote job interviews.',
    readTime: '11 min',
    date: '2026-02-18',
    tag: 'Essential',
    emoji: '🤝',
    image: '/images/guides/what-to-wear-job-interview-2026.svg',
    affiliateProducts: [
      { name: 'Navy Tailored Blazer', brand: 'Amazon', price: '$49', url: 'https://amzn.to/4rVjOFg', tag: 'Corporate Pick', image: '/images/products/navy-tailored-blazer.svg' },
      { name: 'Slim Dress Pants', brand: 'Amazon', price: '$38', url: 'https://amzn.to/3ZCaw4S', image: '/images/products/slim-dress-pants.svg' },
      { name: 'Pointed Toe Pumps', brand: 'Amazon', price: '$45', url: 'https://amzn.to/3OhrhzW', tag: 'Comfort Pick', image: '/images/products/pointed-toe-pumps.svg' },
      { name: 'Structured Handbag', brand: 'Amazon', price: '$35', url: 'https://amzn.to/4anggFT', image: '/images/products/structured-handbag.svg' },
    ],
  },
  {
    slug: 'spring-2026-must-have-items',
    title: '10 Must-Have Fashion Items for Spring 2026: Runway to Real Life',
    category: 'seasonal',
    description: 'From leather jackets to vanilla yellow tops — the 10 hottest spring 2026 trend items straight from the runway, all shoppable on Amazon.',
    readTime: '14 min',
    date: '2026-02-18',
    tag: 'Hot',
    emoji: '🔥',
    image: '/images/guides/spring-2026-must-have-items.svg',
    affiliateProducts: [
      { name: 'Leather Jacket', brand: 'Amazon', price: '$59', url: 'https://amzn.to/4az8Vlh', tag: '#1 Must Have', image: '/images/products/leather-jacket.svg' },
      { name: 'Cigarette Jeans', brand: 'Amazon', price: '$42', url: 'https://amzn.to/4kJhrTx', tag: 'Trending', image: '/images/products/cigarette-jeans.svg' },
      { name: 'Large Tote Bag', brand: 'Amazon', price: '$36', url: 'https://amzn.to/4qBF7dJ', image: '/images/products/large-tote-bag.svg' },
      { name: 'Oversized Trench Coat', brand: 'Amazon', price: '$68', url: 'https://amzn.to/4kNVNxy', tag: 'Investment Piece', image: '/images/products/oversized-trench-coat.svg' },
      { name: 'Vanilla Yellow Blouse', brand: 'Amazon', price: '$28', url: 'https://amzn.to/4rUPDhk', tag: 'IT Color 2026', image: '/images/products/vanilla-yellow-blouse.svg' },
    ],
  },
  {
    slug: 'trending-spring-accessories-2026',
    title: 'Spring 2026 Accessories: Bags, Shoes & Jewelry Trends',
    category: 'seasonal',
    description: 'Complete your spring look with these trending accessories — from oversized sunglasses to almond toe heels, all under $70.',
    readTime: '12 min',
    date: '2026-02-18',
    tag: 'Trending',
    emoji: '👛',
    image: '/images/guides/trending-spring-accessories-2026.svg',
    affiliateProducts: [
      { name: 'Lace Midi Skirt', brand: 'Amazon', price: '$32', url: 'https://amzn.to/3OrVpsf', tag: 'Romantic Trend', image: '/images/products/lace-midi-skirt.svg' },
      { name: 'Quarter Zip Knit', brand: 'Amazon', price: '$35', url: 'https://amzn.to/40drBCf', tag: 'Runway Pick', image: '/images/products/quarter-zip-knit.svg' },
      { name: 'Floral Midi Dress', brand: 'Amazon', price: '$38', url: 'https://amzn.to/4rfX7eQ', tag: 'Spring Essential', image: '/images/products/floral-midi-dress.svg' },
      { name: 'Oversized Sunglasses', brand: 'Amazon', price: '$18', url: 'https://amzn.to/4tEIRhl', tag: 'Statement Piece', image: '/images/products/oversized-sunglasses.svg' },
      { name: 'Almond Toe Heels', brand: 'Amazon', price: '$45', url: 'https://amzn.to/4tEJV4X', tag: 'Elegant Pick', image: '/images/products/almond-toe-heels.svg' },
    ],
  },
  // ===== NEW HIGH-REVENUE GUIDES =====
  {
    slug: 'best-running-shoes-women-2026',
    title: 'The 10 Best Running Shoes for Women in 2026 (Tested by Runners)',
    category: 'casual',
    description: 'We tested 30+ running shoes across road, trail, and treadmill. These are the best picks for comfort, support, and performance at every price point.',
    readTime: '16 min',
    date: '2026-02-19',
    tag: 'Product Review',
    emoji: '🏃‍♀️',
    image: '/images/guides/best-running-shoes-women-2026.svg',
    affiliateProducts: [
      { name: 'Lightweight Running Shoes', brand: 'Amazon', price: '$65', url: 'https://amzn.to/3Mro7cj', tag: 'Best Overall', image: '/images/products/lightweight-running-shoes.svg' },
      { name: 'Cushioned Trail Runners', brand: 'Amazon', price: '$72', url: 'https://amzn.to/3OhrhzW', tag: 'Best for Trails', image: '/images/products/cushioned-trail-runners.svg' },
      { name: 'Budget Running Shoes', brand: 'Amazon', price: '$45', url: 'https://amzn.to/4rfVnSQ', tag: 'Best Value', image: '/images/products/budget-running-shoes.svg' },
      { name: 'Running Leggings', brand: 'Amazon', price: '$32', url: 'https://amzn.to/3ZCaw4S', tag: 'Pair With', image: '/images/products/running-leggings.svg' },
      { name: 'Sports Bra (High Impact)', brand: 'Amazon', price: '$28', url: 'https://amzn.to/3Mro3JB', tag: 'Essential', image: '/images/products/sports-bra-high-impact.svg' },
    ],
  },
  {
    slug: 'best-laptop-bags-women-2026',
    title: 'The 12 Best Laptop Bags for Women in 2026: Stylish & Functional',
    category: 'workwear',
    description: 'Carry your tech in style. These laptop bags fit 13-16 inch laptops while looking chic enough for client meetings, commutes, and travel.',
    readTime: '14 min',
    date: '2026-02-19',
    tag: 'Product Review',
    emoji: '💻',
    image: '/images/guides/best-laptop-bags-women-2026.svg',
    affiliateProducts: [
      { name: 'Leather Laptop Tote', brand: 'Amazon', price: '$58', url: 'https://amzn.to/4anggFT', tag: 'Best Overall', image: '/images/products/leather-laptop-tote.svg' },
      { name: 'Laptop Backpack (Slim)', brand: 'Amazon', price: '$42', url: 'https://amzn.to/4qBF7dJ', tag: 'Best for Commute', image: '/images/products/laptop-backpack-slim.svg' },
      { name: 'Convertible Messenger Bag', brand: 'Amazon', price: '$48', url: 'https://amzn.to/4rVjOFg', tag: 'Most Versatile', image: '/images/products/convertible-messenger-bag.svg' },
      { name: 'Laptop Sleeve (Padded)', brand: 'Amazon', price: '$22', url: 'https://amzn.to/3Mro3JB', tag: 'Budget Pick', image: '/images/products/laptop-sleeve-padded.svg' },
      { name: 'Structured Work Blazer', brand: 'Amazon', price: '$49', url: 'https://amzn.to/4rVjOFg', tag: 'Complete the Look', image: '/images/products/structured-work-blazer.svg' },
    ],
  },
  {
    slug: 'best-sunglasses-face-shape-2026',
    title: 'Best Sunglasses for Your Face Shape 2026: The Complete Guide',
    category: 'body-type',
    description: 'Round, oval, square, or heart-shaped face? Find the perfect sunglasses that flatter your features — all under $50 on Amazon.',
    readTime: '13 min',
    date: '2026-02-19',
    tag: 'Guide',
    emoji: '🕶️',
    image: '/images/guides/best-sunglasses-face-shape-2026.svg',
    affiliateProducts: [
      { name: 'Oversized Square Sunglasses', brand: 'Amazon', price: '$18', url: 'https://amzn.to/4tEIRhl', tag: 'Best for Round Face', image: '/images/products/oversized-square-sunglasses.svg' },
      { name: 'Cat Eye Sunglasses', brand: 'Amazon', price: '$22', url: 'https://amzn.to/3Mro3JB', tag: 'Best for Oval Face', image: '/images/products/cat-eye-sunglasses.svg' },
      { name: 'Round Sunglasses', brand: 'Amazon', price: '$16', url: 'https://amzn.to/4rfVnSQ', tag: 'Best for Square Face', image: '/images/products/round-sunglasses.svg' },
      { name: 'Aviator Sunglasses', brand: 'Amazon', price: '$20', url: 'https://amzn.to/3OhrhzW', tag: 'Best for Heart Face', image: '/images/products/aviator-sunglasses.svg' },
      { name: 'Polarized Sport Sunglasses', brand: 'Amazon', price: '$25', url: 'https://amzn.to/3ZCaw4S', tag: 'Best for Active', image: '/images/products/polarized-sport-sunglasses.svg' },
    ],
  },
  {
    slug: 'amazon-fashion-finds-under-30',
    title: 'Amazon Fashion Finds Under $30: 25 Items That Look Designer',
    category: 'budget',
    description: 'The best Amazon fashion finds under $30 that look way more expensive than they are. From Editor\'s Choice picks to hidden gems, all rated 4+ stars.',
    readTime: '15 min',
    date: '2026-02-19',
    tag: 'Viral',
    emoji: '🔥',
    image: '/images/guides/amazon-fashion-finds-under-30.svg',
    affiliateProducts: [
      { name: 'Satin Pleated Skirt', brand: 'Amazon', price: '$26', url: 'https://amzn.to/3OrVpsf', tag: 'Editor\'s Choice', image: '/images/products/satin-pleated-skirt.svg' },
      { name: 'Oversized Linen Shirt', brand: 'Amazon', price: '$28', url: 'https://amzn.to/4rUPDhk', tag: 'Most Versatile', image: '/images/products/oversized-linen-shirt.svg' },
      { name: 'Gold Layered Necklace Set', brand: 'Amazon', price: '$14', url: 'https://amzn.to/3Mro3JB', tag: 'Best Under $15', image: '/images/products/gold-layered-necklace-set.svg' },
      { name: 'Ribbed Bodysuit', brand: 'Amazon', price: '$18', url: 'https://amzn.to/4tH7kT9', tag: 'Wardrobe Staple', image: '/images/products/ribbed-bodysuit.svg' },
      { name: 'Crossbody Bag', brand: 'Amazon', price: '$24', url: 'https://amzn.to/4anggFT', tag: 'Best Seller', image: '/images/products/crossbody-bag.svg' },
    ],
  },
  {
    slug: 'summer-fashion-essentials-2026',
    title: 'Summer 2026 Fashion Essentials: Your Complete Warm Weather Guide',
    category: 'seasonal',
    description: 'Beat the heat in style with these summer wardrobe essentials — lightweight fabrics, flattering swimwear, and vacation-ready outfits all under $60.',
    readTime: '14 min',
    date: '2026-02-19',
    tag: 'Seasonal',
    emoji: '☀️',
    image: '/images/guides/summer-fashion-essentials-2026.svg',
    affiliateProducts: [
      { name: 'Linen Wide Leg Pants', brand: 'Amazon', price: '$34', url: 'https://amzn.to/3ZCaw4S', tag: 'Summer Staple', image: '/images/products/linen-wide-leg-pants.svg' },
      { name: 'Cotton Sundress', brand: 'Amazon', price: '$29', url: 'https://amzn.to/4tH7kT9', tag: 'Best Seller', image: '/images/products/cotton-sundress.svg' },
      { name: 'Straw Tote Bag', brand: 'Amazon', price: '$26', url: 'https://amzn.to/4anggFT', tag: 'Beach Ready', image: '/images/products/straw-tote-bag.svg' },
      { name: 'Flat Sandals (Leather)', brand: 'Amazon', price: '$32', url: 'https://amzn.to/3OhrhzW', tag: 'Most Comfortable', image: '/images/products/flat-sandals-leather.svg' },
      { name: 'Oversized Sunglasses', brand: 'Amazon', price: '$18', url: 'https://amzn.to/4tEIRhl', tag: 'UV Protection', image: '/images/products/oversized-sunglasses.svg' },
    ],
  },
  // ===== HIGH-TRAFFIC SEO GUIDES =====
  {
    slug: 'plus-size-fashion-guide-2026',
    title: 'Plus Size Fashion Guide 2026: Stylish Outfits for Every Occasion',
    category: 'body-type',
    description: 'Look and feel amazing in every outfit. The ultimate plus size fashion guide with flattering silhouettes, styling tips, and shoppable looks from $20.',
    readTime: '15 min',
    date: '2026-02-20',
    tag: 'Pillar Guide',
    emoji: '💗',
    image: '/images/guides/plus-size-fashion-guide-2026.svg',
    affiliateProducts: [
      { name: 'Wrap Maxi Dress', brand: 'Amazon', price: '$38', url: 'https://amzn.to/4tH7kT9', tag: 'Best Seller', image: '/images/products/wrap-maxi-dress.svg' },
      { name: 'High-Waist Wide Leg Pants', brand: 'Amazon', price: '$36', url: 'https://amzn.to/3ZCaw4S', tag: 'Most Flattering', image: '/images/products/high-waist-wide-leg-pants.svg' },
      { name: 'Structured Blazer', brand: 'Amazon', price: '$49', url: 'https://amzn.to/4rVjOFg', tag: 'Editor Pick', image: '/images/products/structured-blazer.svg' },
      { name: 'Stretchy Bodycon Dress', brand: 'Amazon', price: '$28', url: 'https://amzn.to/4rfVnSQ', tag: 'Date Night', image: '/images/products/stretchy-bodycon-dress.svg' },
      { name: 'Block Heel Sandals (Wide)', brand: 'Amazon', price: '$42', url: 'https://amzn.to/3OhrhzW', tag: 'Comfort Pick', image: '/images/products/block-heel-sandals-wide.svg' },
    ],
  },
  {
    slug: 'fall-fashion-trends-2026',
    title: 'Fall 2026 Fashion Trends: Complete Guide to Autumn Style',
    category: 'seasonal',
    description: 'Everything you need to know about fall 2026 fashion trends — from cozy knitwear to bold leather pieces. Shop the season\'s best looks under $75.',
    readTime: '14 min',
    date: '2026-02-20',
    tag: 'Trending',
    emoji: '🍂',
    image: '/images/guides/fall-fashion-trends-2026.svg',
    affiliateProducts: [
      { name: 'Chunky Knit Sweater', brand: 'Amazon', price: '$42', url: 'https://amzn.to/40drBCf', tag: 'Fall Essential', image: '/images/products/chunky-knit-sweater.svg' },
      { name: 'Faux Leather Trousers', brand: 'Amazon', price: '$48', url: 'https://amzn.to/3ZCaw4S', tag: 'Trending', image: '/images/products/faux-leather-trousers.svg' },
      { name: 'Ankle Boots', brand: 'Amazon', price: '$55', url: 'https://amzn.to/3OhrhzW', tag: 'Must Have', image: '/images/products/ankle-boots.svg' },
      { name: 'Oversized Trench Coat', brand: 'Amazon', price: '$68', url: 'https://amzn.to/4kNVNxy', tag: 'Investment Piece', image: '/images/products/oversized-trench-coat.svg' },
      { name: 'Plaid Mini Skirt', brand: 'Amazon', price: '$32', url: 'https://amzn.to/3OrVpsf', tag: 'Viral Pick', image: '/images/products/plaid-mini-skirt.svg' },
    ],
  },
  {
    slug: 'petite-fashion-guide-2026',
    title: 'Petite Fashion Guide 2026: Outfits That Make You Look Taller',
    category: 'body-type',
    description: 'Dressing for a petite frame has never been easier. These styling tricks, silhouettes, and shoppable Amazon picks will transform your wardrobe.',
    readTime: '13 min',
    date: '2026-02-20',
    tag: 'Guide',
    emoji: '✨',
    image: '/images/guides/petite-fashion-guide-2026.svg',
    affiliateProducts: [
      { name: 'High-Waist Skinny Jeans', brand: 'Amazon', price: '$36', url: 'https://amzn.to/4rfVnSQ', tag: 'Best for Petite', image: '/images/products/high-waist-skinny-jeans.svg' },
      { name: 'Midi Dress with Belt', brand: 'Amazon', price: '$34', url: 'https://amzn.to/4tH7kT9', tag: 'Elongating', image: '/images/products/midi-dress-with-belt.svg' },
      { name: 'Pointed Toe Kitten Heels', brand: 'Amazon', price: '$42', url: 'https://amzn.to/3OhrhzW', tag: 'Height Boost', image: '/images/products/pointed-toe-kitten-heels.svg' },
      { name: 'Cropped Blazer', brand: 'Amazon', price: '$45', url: 'https://amzn.to/4rVjOFg', tag: 'Perfect Length', image: '/images/products/cropped-blazer.svg' },
    ],
  },
  {
    slug: 'amazon-prime-fashion-deals-2026',
    title: 'Best Amazon Prime Fashion Deals 2026: Editor\'s Top 30 Picks',
    category: 'budget',
    description: 'Shop the best Amazon Prime fashion deals — curated by our editors. Top-rated clothing, shoes, and accessories with Prime delivery, all under $60.',
    readTime: '12 min',
    date: '2026-02-20',
    tag: 'Viral',
    emoji: '🛒',
    image: '/images/guides/amazon-prime-fashion-deals-2026.svg',
    affiliateProducts: [
      { name: 'Fleece Pullover Hoodie', brand: 'Amazon', price: '$32', url: 'https://amzn.to/40drBCf', tag: '#1 Best Seller', image: '/images/products/fleece-pullover-hoodie.svg' },
      { name: 'Yoga Pants (High Waist)', brand: 'Amazon', price: '$28', url: 'https://amzn.to/3ZCaw4S', tag: 'Most Reviewed', image: '/images/products/yoga-pants-high-waist.svg' },
      { name: 'Satin Slip Dress', brand: 'Amazon', price: '$29', url: 'https://amzn.to/4tH7kT9', tag: 'Editor\'s Choice', image: '/images/products/satin-slip-dress.svg' },
      { name: 'V-Neck Cardigan', brand: 'Amazon', price: '$34', url: 'https://amzn.to/3Mro3JB', tag: 'Prime Pick', image: '/images/products/v-neck-cardigan.svg' },
      { name: 'Platform Sneakers', brand: 'Amazon', price: '$48', url: 'https://amzn.to/3Mro7cj', tag: 'Editor Pick', image: '/images/products/platform-sneakers.svg' },
    ],
  },
  {
    slug: 'how-to-dress-for-your-age-50s',
    title: 'How to Dress in Your 50s: Stylish Outfits for Women Over 50',
    category: 'occasion',
    description: 'Fashion doesn\'t have age limits. Discover the most flattering and chic outfit ideas for women in their 50s — elegant, modern, and totally shoppable.',
    readTime: '13 min',
    date: '2026-02-20',
    tag: 'Popular',
    emoji: '👑',
    image: '/images/guides/how-to-dress-in-your-50s.svg',
    affiliateProducts: [
      { name: 'Tailored Ponte Blazer', brand: 'Amazon', price: '$52', url: 'https://amzn.to/4rVjOFg', tag: 'Age-Elegant', image: '/images/products/tailored-ponte-blazer.svg' },
      { name: 'Straight Leg Jeans (Mid Rise)', brand: 'Amazon', price: '$42', url: 'https://amzn.to/4rfVnSQ', tag: 'Most Comfortable', image: '/images/products/straight-leg-jeans-mid-rise.svg' },
      { name: 'Silk Blouse (Plus & Standard)', brand: 'Amazon', price: '$35', url: 'https://amzn.to/3Mro3JB', tag: 'Best Quality', image: '/images/products/silk-blouse-plus-standard.svg' },
      { name: 'Block Heel Pumps', brand: 'Amazon', price: '$48', url: 'https://amzn.to/3OhrhzW', tag: 'Comfort + Style', image: '/images/products/block-heel-pumps.svg' },
    ],
  },
  {
    slug: 'best-gym-workout-outfits-women-2026',
    title: 'Best Gym Outfits for Women 2026: Stylish Activewear Under $50',
    category: 'casual',
    description: 'Sweat in style with these editor-tested gym outfits. The best activewear sets, sports bras, and leggings that perform as well as they look.',
    readTime: '12 min',
    date: '2026-02-20',
    tag: 'Product Review',
    emoji: '💪',
    image: '/images/guides/best-gym-outfits-women-2026.svg',
    affiliateProducts: [
      { name: 'High-Waist Workout Leggings', brand: 'Amazon', price: '$32', url: 'https://amzn.to/3ZCaw4S', tag: 'Best Overall', image: '/images/products/high-waist-workout-leggings.svg' },
      { name: 'Seamless Sports Bra', brand: 'Amazon', price: '$22', url: 'https://amzn.to/3Mro3JB', tag: 'Top Rated', image: '/images/products/seamless-sports-bra.svg' },
      { name: 'Oversized Gym T-Shirt', brand: 'Amazon', price: '$18', url: 'https://amzn.to/3Mro7cj', tag: 'Best Value', image: '/images/products/oversized-gym-t-shirt.svg' },
      { name: 'Running Sneakers', brand: 'Amazon', price: '$58', url: 'https://amzn.to/4rfVnSQ', tag: 'Editor Pick', image: '/images/products/running-sneakers.svg' },
      { name: 'Gym Duffel Bag', brand: 'Amazon', price: '$28', url: 'https://amzn.to/4anggFT', tag: 'Must Have', image: '/images/products/gym-duffel-bag.svg' },
    ],
  },
  {
    slug: 'vacation-outfits-women-2026',
    title: 'Vacation Outfits for Women 2026: Packing List & Style Guide',
    category: 'occasion',
    description: 'Pack smart, look stunning. The ultimate vacation packing guide with 20+ outfit ideas for beaches, cities, resorts, and tropical destinations.',
    readTime: '15 min',
    date: '2026-02-20',
    tag: 'Hot',
    emoji: '🌴',
    image: '/images/guides/vacation-outfits-women-2026.svg',
    affiliateProducts: [
      { name: 'Linen Button-Up Shirt Dress', brand: 'Amazon', price: '$38', url: 'https://amzn.to/4tH7kT9', tag: 'Vacation Staple', image: '/images/products/linen-button-up-shirt-dress.svg' },
      { name: 'Bikini Set (Adjustable)', brand: 'Amazon', price: '$28', url: 'https://amzn.to/4rfVnSQ', tag: 'Best Seller', image: '/images/products/bikini-set-adjustable.svg' },
      { name: 'Straw Hat (Beach)', brand: 'Amazon', price: '$22', url: 'https://amzn.to/4tEIRhl', tag: 'Must Pack', image: '/images/products/straw-hat-beach.svg' },
      { name: 'Lightweight Sandals', brand: 'Amazon', price: '$29', url: 'https://amzn.to/3OhrhzW', tag: 'Most Comfortable', image: '/images/products/lightweight-sandals.svg' },
      { name: 'Rattan Crossbody Bag', brand: 'Amazon', price: '$26', url: 'https://amzn.to/4anggFT', tag: 'Beach Chic', image: '/images/products/rattan-crossbody-bag.svg' },
    ],
  },
  {
    slug: 'editors-choice-fashion-trends-2026',
    title: 'Fashion Trends 2026: Every Editor\'s Choice Style Explained',
    category: 'casual',
    description: 'From quiet luxury to balletcore and beyond -- a complete breakdown of 2026\'s biggest Editor\'s Choice fashion trends with shoppable Amazon links.',
    readTime: '13 min',
    date: '2026-02-20',
    tag: 'Viral',
    emoji: '🎵',
    image: '/images/guides/editors-choice-fashion-trends-2026.svg',
    affiliateProducts: [
      { name: 'Ballet Flat (Square Toe)', brand: 'Amazon', price: '$38', url: 'https://amzn.to/3OhrhzW', tag: 'Balletcore', image: '/images/products/ballet-flat-square-toe.svg' },
      { name: 'Cashmere Blend Sweater', brand: 'Amazon', price: '$55', url: 'https://amzn.to/40drBCf', tag: 'Quiet Luxury', image: '/images/products/cashmere-blend-sweater.svg' },
      { name: 'Barrel Leg Jeans', brand: 'Amazon', price: '$42', url: 'https://amzn.to/4rfVnSQ', tag: 'Viral Denim', image: '/images/products/barrel-leg-jeans.svg' },
      { name: 'Mesh Ballet Skirt', brand: 'Amazon', price: '$28', url: 'https://amzn.to/3OrVpsf', tag: 'Editor\'s Pick', image: '/images/products/mesh-ballet-skirt.svg' },
    ],
  },
  {
    slug: 'how-to-style-oversized-blazer',
    title: 'How to Style an Oversized Blazer: 15 Outfit Ideas for 2026',
    category: 'casual',
    description: 'The oversized blazer is 2026\'s most versatile piece. Here\'s how to style it 15 different ways — from office-ready to weekend casual.',
    readTime: '11 min',
    date: '2026-02-20',
    tag: 'Style Tips',
    emoji: '🧥',
    image: '/images/guides/how-to-style-oversized-blazer.svg',
    affiliateProducts: [
      { name: 'Oversized Blazer (Neutral)', brand: 'Amazon', price: '$49', url: 'https://amzn.to/4rVjOFg', tag: 'Hero Piece', image: '/images/products/oversized-blazer-neutral.svg' },
      { name: 'Biker Shorts', brand: 'Amazon', price: '$22', url: 'https://amzn.to/3ZCaw4S', tag: 'Style With', image: '/images/products/biker-shorts.svg' },
      { name: 'Pointed Toe Boots', brand: 'Amazon', price: '$52', url: 'https://amzn.to/3OhrhzW', tag: 'Best Pairing', image: '/images/products/pointed-toe-boots.svg' },
      { name: 'White Straight Leg Jeans', brand: 'Amazon', price: '$38', url: 'https://amzn.to/4rfVnSQ', tag: 'Classic Combo', image: '/images/products/white-straight-leg-jeans.svg' },
    ],
  },
  {
    slug: 'best-dresses-for-wedding-guest-under-100',
    title: 'Best Wedding Guest Dresses Under $100 in 2026: 20 Editor Picks',
    category: 'occasion',
    description: 'Stunning wedding guest dresses that won\'t break the bank. 20 beautiful picks for every dress code, season, and body type — all under $100.',
    readTime: '14 min',
    date: '2026-02-20',
    tag: 'Popular',
    emoji: '💒',
    image: '/images/guides/best-wedding-guest-dresses-under-100.svg',
    affiliateProducts: [
      { name: 'Floral Midi Wrap Dress', brand: 'Amazon', price: '$48', url: 'https://amzn.to/4tH7kT9', tag: 'Garden Wedding', image: '/images/products/floral-midi-wrap-dress.webp' },
      { name: 'Chiffon Maxi Dress', brand: 'Amazon', price: '$55', url: 'https://amzn.to/4rfVnSQ', tag: 'Formal Pick', image: '/images/products/chiffon-maxi-dress.svg' },
      { name: 'Satin Slip Midi Dress', brand: 'Amazon', price: '$42', url: 'https://amzn.to/3OrVpsf', tag: 'Modern Classic', image: '/images/products/satin-slip-midi-dress.svg' },
      { name: 'Strappy Heeled Sandals', brand: 'Amazon', price: '$45', url: 'https://amzn.to/3OhrhzW', tag: 'Complete the Look', image: '/images/products/strappy-heeled-sandals.svg' },
      { name: 'Beaded Clutch', brand: 'Amazon', price: '$28', url: 'https://amzn.to/4anggFT', tag: 'Elegant Touch', image: '/images/products/beaded-clutch.svg' },
    ],
  },
  {
    slug: 'winter-fashion-essentials-2026',
    title: 'Winter Fashion Essentials 2026: Your Complete Cold Weather Wardrobe',
    category: 'seasonal',
    description: 'Stay warm and stylish all winter with these essential pieces. From cozy coats to layering basics, build a winter wardrobe that works for every occasion.',
    readTime: '14 min',
    date: '2026-02-21',
    tag: 'Seasonal',
    emoji: '❄️',
    image: '/images/guides/winter-fashion-essentials-2026.svg',
    affiliateProducts: [
      { name: 'Wool Blend Coat', brand: 'Amazon', price: '$78', url: 'https://amzn.to/4kNVNxy', tag: 'Best Overall', image: '/images/products/wool-blend-coat.svg' },
      { name: 'Cashmere Turtleneck Sweater', brand: 'Amazon', price: '$45', url: 'https://amzn.to/40drBCf', tag: 'Editor Pick', image: '/images/products/cashmere-turtleneck-sweater.svg' },
      { name: 'Thermal Lined Leggings', brand: 'Amazon', price: '$28', url: 'https://amzn.to/3ZCaw4S', tag: 'Warmest Pick', image: '/images/products/thermal-lined-leggings.svg' },
      { name: 'Knee-High Boots', brand: 'Amazon', price: '$65', url: 'https://amzn.to/3OhrhzW', tag: 'Must Have', image: '/images/products/knee-high-boots.svg' },
      { name: 'Chunky Knit Scarf', brand: 'Amazon', price: '$22', url: 'https://amzn.to/3Mro3JB', tag: 'Cozy Essential', image: '/images/products/chunky-knit-scarf.svg' },
    ],
  },
  {
    slug: 'business-casual-outfits-women-2026',
    title: 'Business Casual Outfits for Women 2026: The Complete Style Guide',
    category: 'workwear',
    description: 'Master the business casual dress code with outfit formulas that are polished without being stuffy. Perfect for hybrid offices, creative workplaces, and client meetings.',
    readTime: '13 min',
    date: '2026-02-21',
    tag: 'Guide',
    emoji: '💼',
    image: '/images/guides/business-casual-outfits-women-2026.svg',
    affiliateProducts: [
      { name: 'Ponte Knit Blazer', brand: 'Amazon', price: '$52', url: 'https://amzn.to/4rVjOFg', tag: 'Best Overall', image: '/images/products/ponte-knit-blazer.svg' },
      { name: 'Wide Leg Dress Pants', brand: 'Amazon', price: '$42', url: 'https://amzn.to/3ZCaw4S', tag: 'Office Staple', image: '/images/products/wide-leg-dress-pants.svg' },
      { name: 'Mock Neck Blouse', brand: 'Amazon', price: '$32', url: 'https://amzn.to/3Mro3JB', tag: 'Editor Pick', image: '/images/products/mock-neck-blouse.svg' },
      { name: 'Pointed Toe Loafers', brand: 'Amazon', price: '$48', url: 'https://amzn.to/3OhrhzW', tag: 'Versatile', image: '/images/products/pointed-toe-loafers.svg' },
      { name: 'Leather Tote Bag', brand: 'Amazon', price: '$55', url: 'https://amzn.to/4anggFT', tag: 'Professional', image: '/images/products/leather-tote-bag.svg' },
    ],
  },
  {
    slug: 'color-theory-fashion-guide',
    title: 'Color Theory for Fashion: How to Build Outfits That Always Work',
    category: 'casual',
    description: 'Stop second-guessing your outfit combinations. Learn the color theory secrets that stylists use to create effortlessly coordinated looks every single time.',
    readTime: '12 min',
    date: '2026-02-21',
    tag: 'Style Tips',
    emoji: '🎨',
    image: '/images/guides/color-theory-fashion-guide.svg',
    affiliateProducts: [
      { name: 'Color Block Sweater', brand: 'Amazon', price: '$35', url: 'https://amzn.to/40drBCf', tag: 'Top Rated', image: '/images/products/color-block-sweater.svg' },
      { name: 'Neutral Tone Midi Skirt', brand: 'Amazon', price: '$30', url: 'https://amzn.to/3OrVpsf', tag: 'Versatile', image: '/images/products/neutral-tone-midi-skirt.svg' },
      { name: 'Silk Scarf (Multi-way)', brand: 'Amazon', price: '$18', url: 'https://amzn.to/3Mro3JB', tag: 'Color Pop', image: '/images/products/silk-scarf-multi-way.svg' },
      { name: 'White Linen Shirt', brand: 'Amazon', price: '$28', url: 'https://amzn.to/4rUPDhk', tag: 'Base Layer', image: '/images/products/white-linen-shirt.svg' },
    ],
  },
  {
    slug: 'brunch-outfits-women-2026',
    title: 'Best Brunch Outfits for Women 2026: Chic & Comfortable Looks',
    category: 'occasion',
    description: 'Look effortlessly put-together at your next brunch date. From casual mimosa mornings to bougie rooftop brunches, these outfits nail every vibe.',
    readTime: '11 min',
    date: '2026-02-21',
    tag: 'Occasion Guide',
    emoji: '🥂',
    image: '/images/guides/best-brunch-outfits-women-2026.svg',
    affiliateProducts: [
      { name: 'Floral Mini Dress', brand: 'Amazon', price: '$34', url: 'https://amzn.to/4tH7kT9', tag: 'Best Seller', image: '/images/products/floral-mini-dress.svg' },
      { name: 'Linen Co-ord Set', brand: 'Amazon', price: '$45', url: 'https://amzn.to/3ZCaw4S', tag: 'Editor Pick', image: '/images/products/linen-co-ord-set.svg' },
      { name: 'Strappy Block Heel Sandals', brand: 'Amazon', price: '$42', url: 'https://amzn.to/3OhrhzW', tag: 'Must Have', image: '/images/products/strappy-block-heel-sandals.svg' },
      { name: 'Woven Straw Bag', brand: 'Amazon', price: '$25', url: 'https://amzn.to/4anggFT', tag: 'Trendy', image: '/images/products/woven-straw-bag.svg' },
      { name: 'Dainty Gold Earrings Set', brand: 'Amazon', price: '$14', url: 'https://amzn.to/3Mro3JB', tag: 'Finishing Touch', image: '/images/products/dainty-gold-earrings-set.svg' },
    ],
  },
  {
    slug: 'best-ankle-boots-women-2026',
    title: 'Best Ankle Boots for Women 2026: Editor-Tested Picks Under $80',
    category: 'budget',
    description: 'The ankle boot is the most versatile shoe you can own. Our editors tested 40+ pairs to find the best ankle boots for every style and budget in 2026.',
    readTime: '13 min',
    date: '2026-02-21',
    tag: 'Product Review',
    emoji: '👢',
    image: '/images/guides/best-ankle-boots-women-2026.svg',
    affiliateProducts: [
      { name: 'Chelsea Ankle Boots', brand: 'Amazon', price: '$58', url: 'https://amzn.to/3OhrhzW', tag: 'Best Overall', image: '/images/products/chelsea-ankle-boots.svg' },
      { name: 'Block Heel Ankle Boots', brand: 'Amazon', price: '$52', url: 'https://amzn.to/4rfVnSQ', tag: 'Best for Work', image: '/images/products/block-heel-ankle-boots.svg' },
      { name: 'Combat Ankle Boots', brand: 'Amazon', price: '$48', url: 'https://amzn.to/3Mro7cj', tag: 'Best Casual', image: '/images/products/combat-ankle-boots.svg' },
      { name: 'Western Ankle Boots', brand: 'Amazon', price: '$62', url: 'https://amzn.to/4kNVNxy', tag: 'Trending', image: '/images/products/western-ankle-boots.svg' },
      { name: 'Pointed Toe Ankle Boots', brand: 'Amazon', price: '$55', url: 'https://amzn.to/4anggFT', tag: 'Most Elegant', image: '/images/products/pointed-toe-ankle-boots.svg' },
    ],
  },
  {
    slug: 'festival-outfits-women-2026',
    title: 'Festival Outfits for Women 2026: Coachella, EDM & Music Festival Style',
    category: 'occasion',
    description: 'Stand out in the crowd with these head-turning festival outfits. From Coachella-ready boho looks to EDM rave styles, we have every festival vibe covered.',
    readTime: '12 min',
    date: '2026-02-21',
    tag: 'Hot',
    emoji: '🎪',
    image: '/images/guides/festival-outfits-women-2026.svg',
    affiliateProducts: [
      { name: 'Crochet Maxi Dress', brand: 'Amazon', price: '$38', url: 'https://amzn.to/4tH7kT9', tag: 'Boho Vibes', image: '/images/products/crochet-maxi-dress.svg' },
      { name: 'Sequin Mini Skirt', brand: 'Amazon', price: '$28', url: 'https://amzn.to/3OrVpsf', tag: 'Rave Ready', image: '/images/products/sequin-mini-skirt.svg' },
      { name: 'Fringe Crop Top', brand: 'Amazon', price: '$22', url: 'https://amzn.to/4rUPDhk', tag: 'Festival Must', image: '/images/products/fringe-crop-top.svg' },
      { name: 'Platform Chunky Sneakers', brand: 'Amazon', price: '$55', url: 'https://amzn.to/3Mro7cj', tag: 'All-Day Comfort', image: '/images/products/platform-chunky-sneakers.svg' },
      { name: 'Boho Bucket Hat', brand: 'Amazon', price: '$18', url: 'https://amzn.to/4tEIRhl', tag: 'Sun Protection', image: '/images/products/boho-bucket-hat.svg' },
    ],
  },
  {
    slug: 'korean-fashion-trends-2026',
    title: 'Korean Fashion Trends 2026: K-Style Guide for Every Aesthetic',
    category: 'casual',
    description: 'Bring K-fashion energy to your wardrobe. From clean girl aesthetic to Y2K-inspired K-pop looks, discover how to dress like your favorite Korean influencers.',
    readTime: '13 min',
    date: '2026-02-21',
    tag: 'Trending',
    emoji: '✨',
    image: '/images/guides/korean-fashion-trends-2026.svg',
    affiliateProducts: [
      { name: 'Oversized Blazer Set', brand: 'Amazon', price: '$55', url: 'https://amzn.to/4rVjOFg', tag: 'K-Style Essential', image: '/images/products/oversized-blazer-set.svg' },
      { name: 'Mini Pleated Skirt', brand: 'Amazon', price: '$25', url: 'https://amzn.to/3OrVpsf', tag: 'Viral Pick', image: '/images/products/mini-pleated-skirt.svg' },
      { name: 'Ribbed Knit Cardigan', brand: 'Amazon', price: '$32', url: 'https://amzn.to/3Mro3JB', tag: 'Clean Girl', image: '/images/products/ribbed-knit-cardigan.svg' },
      { name: 'Mary Jane Platform Shoes', brand: 'Amazon', price: '$48', url: 'https://amzn.to/4rfVnSQ', tag: 'K-Pop Inspired', image: '/images/products/mary-jane-platform-shoes.svg' },
      { name: 'Micro Shoulder Bag', brand: 'Amazon', price: '$28', url: 'https://amzn.to/4anggFT', tag: 'Aesthetic Pick', image: '/images/products/micro-shoulder-bag.svg' },
    ],
  },
  {
    slug: 'hourglass-figure-style-guide',
    title: 'How to Dress an Hourglass Figure: The Complete Style Guide 2026',
    category: 'body-type',
    description: 'Show off your curves in all the right ways. The definitive guide to dressing an hourglass figure with outfit formulas that balance proportions and flatter your shape.',
    readTime: '13 min',
    date: '2026-02-21',
    tag: 'Guide',
    emoji: '⏳',
    image: '/images/guides/hourglass-figure-style-guide.svg',
    affiliateProducts: [
      { name: 'Wrap Midi Dress', brand: 'Amazon', price: '$38', url: 'https://amzn.to/4tH7kT9', tag: 'Most Flattering', image: '/images/products/wrap-midi-dress.svg' },
      { name: 'Belted Trench Coat', brand: 'Amazon', price: '$65', url: 'https://amzn.to/4kNVNxy', tag: 'Editor Pick', image: '/images/products/belted-trench-coat.svg' },
      { name: 'High Waist Pencil Skirt', brand: 'Amazon', price: '$32', url: 'https://amzn.to/3OrVpsf', tag: 'Classic Choice', image: '/images/products/high-waist-pencil-skirt.svg' },
      { name: 'Fitted Ribbed Bodysuit', brand: 'Amazon', price: '$22', url: 'https://amzn.to/4tH7kT9', tag: 'Wardrobe Essential', image: '/images/products/fitted-ribbed-bodysuit.svg' },
    ],
  },
  {
    slug: 'smart-casual-outfits-women-2026',
    title: 'Smart Casual Outfits for Women 2026: The Dress Code Explained',
    category: 'casual',
    description: 'Smart casual is the trickiest dress code to nail — not too formal, not too relaxed. These outfit formulas solve the smart casual puzzle for every occasion.',
    readTime: '12 min',
    date: '2026-02-21',
    tag: 'Style Guide',
    emoji: '✨',
    image: '/images/guides/smart-casual-outfits-women-2026.svg',
    affiliateProducts: [
      { name: 'Straight Leg Dark Jeans', brand: 'Amazon', price: '$40', url: 'https://amzn.to/4rfVnSQ', tag: 'Smart Casual Staple', image: '/images/products/straight-leg-dark-jeans.svg' },
      { name: 'Silk Blend Blouse', brand: 'Amazon', price: '$35', url: 'https://amzn.to/3Mro3JB', tag: 'Elevated Basic', image: '/images/products/silk-blend-blouse.svg' },
      { name: 'Tailored Blazer', brand: 'Amazon', price: '$49', url: 'https://amzn.to/4rVjOFg', tag: 'Must Have', image: '/images/products/tailored-blazer.svg' },
      { name: 'White Leather Sneakers', brand: 'Amazon', price: '$45', url: 'https://amzn.to/3Mro7cj', tag: 'Casual Lift', image: '/images/products/white-leather-sneakers.svg' },
      { name: 'Structured Crossbody Bag', brand: 'Amazon', price: '$38', url: 'https://amzn.to/4anggFT', tag: 'Polish Touch', image: '/images/products/structured-crossbody-bag.svg' },
    ],
  },
  {
    slug: 'best-accessories-under-50-2026',
    title: 'Best Fashion Accessories Under $50 in 2026: Jewelry, Bags & More',
    category: 'budget',
    description: 'The right accessories can transform any outfit. Discover the best fashion accessories under $50 — necklaces, earrings, bags, and belts that look way more expensive.',
    readTime: '12 min',
    date: '2026-02-21',
    tag: 'Budget Picks',
    emoji: '💎',
    image: '/images/guides/best-accessories-under-50-2026.svg',
    affiliateProducts: [
      { name: 'Gold Layered Necklace Set', brand: 'Amazon', price: '$16', url: 'https://amzn.to/3Mro3JB', tag: 'Best Jewelry', image: '/images/products/gold-layered-necklace-set.svg' },
      { name: 'Reversible Leather Belt', brand: 'Amazon', price: '$22', url: 'https://amzn.to/4rfVnSQ', tag: 'Best Value', image: '/images/products/reversible-leather-belt.svg' },
      { name: 'Mini Shoulder Bag', brand: 'Amazon', price: '$32', url: 'https://amzn.to/4anggFT', tag: 'Best Bag', image: '/images/products/mini-shoulder-bag.svg' },
      { name: 'Pearl Drop Earrings', brand: 'Amazon', price: '$14', url: 'https://amzn.to/3Mro3JB', tag: 'Editor Pick', image: '/images/products/pearl-drop-earrings.webp' },
      { name: 'Silk Hair Scrunchies Set', brand: 'Amazon', price: '$12', url: 'https://amzn.to/4tEIRhl', tag: 'Trending', image: '/images/products/silk-hair-scrunchies-set.svg' },
    ],
  },
  {
    slug: 'quiet-luxury-style-guide-2026',
    title: 'Quiet Luxury Style Guide 2026: How to Nail the Old Money Aesthetic on Any Budget',
    category: 'casual',
    description: 'Master the quiet luxury trend with timeless, understated pieces that look expensive without the designer price tag. Your complete guide to the old money aesthetic.',
    readTime: '11 min',
    date: '2026-02-19',
    tag: 'Hot',
    emoji: '🤍',
    image: '/images/guides/quiet-luxury-style-guide-2026.svg',
    affiliateProducts: [
      { name: 'Cashmere-Blend Crewneck Sweater', brand: 'Amazon', price: '$45', url: 'https://amzn.to/40drBCf', tag: 'Editor Pick', image: '/images/products/cashmere-blend-crewneck-sweater.svg' },
      { name: 'Tailored Wide-Leg Trousers', brand: 'Amazon', price: '$42', url: 'https://amzn.to/3ZCaw4S', tag: 'Best Seller', image: '/images/products/tailored-wide-leg-trousers.svg' },
      { name: 'Classic Wool-Blend Coat', brand: 'Amazon', price: '$68', url: 'https://amzn.to/4kNVNxy', tag: 'Investment Piece', image: '/images/products/classic-wool-blend-coat.svg' },
      { name: 'Leather Ballet Flats', brand: 'Amazon', price: '$38', url: 'https://amzn.to/3OhrhzW', tag: 'Must Have', image: '/images/products/leather-ballet-flats.svg' },
      { name: 'Minimalist Gold Jewelry Set', brand: 'Amazon', price: '$22', url: 'https://amzn.to/3Mro3JB', tag: 'Best Value', image: '/images/products/minimalist-gold-jewelry-set.svg' },
    ],
  },
  {
    slug: 'how-to-style-leather-jacket-women-2026',
    title: 'How to Style a Leather Jacket for Women in 2026: 15+ Outfit Ideas for Every Occasion',
    category: 'casual',
    description: 'Learn how to style a leather jacket for women in 2026. Outfit ideas for work, dates, weekends & more. Find the best leather jackets to buy now.',
    readTime: '11 min',
    date: '2026-02-21',
    tag: 'Style Tips',
    emoji: '🧥',
    image: '/images/guides/how-to-style-leather-jacket-women.svg',
    affiliateProducts: [
      { name: 'AllSaints Balfern Leather Biker Jacket', brand: 'Amazon', price: '$499', url: 'https://amzn.to/4rVjOFg', tag: 'Best Overall', image: '/images/products/allsaints-balfern-leather-biker-jacket.svg' },
      { name: 'Levi\'s Faux Leather Moto Jacket', brand: 'Amazon', price: '$89', url: 'https://amzn.to/3OhrhzW', tag: 'Budget Pick', image: '/images/products/levi.svg' },
      { name: 'Madewell Washed Leather Motorcycle Jacket', brand: 'Amazon', price: '$548', url: 'https://amzn.to/40drBCf', tag: 'Editor\'s Choice', image: '/images/products/madewell-washed-leather-motorcycle-jacket.svg' },
      { name: 'BLANKNYC Faux Leather Jacket', brand: 'Amazon', price: '$98', url: 'https://amzn.to/4tEIRhl', tag: 'Most Popular', image: '/images/products/blanknyc-faux-leather-jacket.svg' },
      { name: 'Sezane Emile Leather Jacket', brand: 'Amazon', price: '$625', url: 'https://amzn.to/4tH7kT9', tag: 'Luxury Pick', image: '/images/products/sezane-emile-leather-jacket.svg' },
    ],
  },
  {
    slug: 'dark-feminine-aesthetic-guide-2026',
    title: 'Dark Feminine Aesthetic 2026: The Ultimate Guide to Mysterious, Powerful Style',
    category: 'date-night',
    description: 'Embrace the dark feminine aesthetic with sultry silhouettes, rich textures, and bold confidence. Your complete guide to the Editor\'s Choice style redefining feminine power.',
    readTime: '10 min',
    date: '2026-02-19',
    tag: 'Trending',
    emoji: '🖤',
    image: '/images/guides/dark-feminine-aesthetic-guide-2026.svg',
    affiliateProducts: [
      { name: 'Satin Corset Top', brand: 'Amazon', price: '$32', url: 'https://amzn.to/4rfVnSQ', tag: 'Best Seller', image: '/images/products/satin-corset-top.svg' },
      { name: 'High-Waist Faux Leather Pants', brand: 'Amazon', price: '$38', url: 'https://amzn.to/3ZCaw4S', tag: 'Must Have', image: '/images/products/high-waist-faux-leather-pants.svg' },
      { name: 'Velvet Blazer', brand: 'Amazon', price: '$55', url: 'https://amzn.to/4rVjOFg', tag: 'Editor Pick', image: '/images/products/velvet-blazer.svg' },
      { name: 'Strappy Block Heel Sandals', brand: 'Amazon', price: '$42', url: 'https://amzn.to/3OhrhzW', tag: 'Date Night', image: '/images/products/strappy-block-heel-sandals.svg' },
      { name: 'Layered Gold Chain Necklace Set', brand: 'Amazon', price: '$18', url: 'https://amzn.to/3Mro3JB', tag: 'Best Value', image: '/images/products/layered-gold-chain-necklace-set.svg' },
    ],
  },
  {
    slug: 'dopamine-dressing-bold-color-outfits-2026',
    title: 'Dopamine Dressing 2026: How Bold Colors Can Transform Your Mood and Your Style',
    category: 'casual',
    description: 'Discover the science behind dopamine dressing and learn how to wear bold, mood-boosting colors with confidence. Outfit ideas, color combos, and affordable picks.',
    readTime: '11 min',
    date: '2026-02-19',
    tag: 'Hot',
    emoji: '\u{1F308}',
    image: '/images/guides/dopamine-dressing-bold-color-outfits.svg',
    affiliateProducts: [
      { name: 'Oversized Satin Blazer in Fuchsia', brand: 'The Drop', price: '$55', url: 'https://amzn.to/4rfVnSQ', tag: 'Editor Pick', image: '/images/products/oversized-satin-blazer-in-fuchsia.svg' },
      { name: 'Wide-Leg Trousers in Cobalt Blue', brand: 'Amazon', price: '$38', url: 'https://amzn.to/3ZCaw4S', tag: 'Best Seller', image: '/images/products/wide-leg-trousers-in-cobalt-blue.svg' },
      { name: 'Chunky Gold Statement Earrings', brand: 'Amazon', price: '$16', url: 'https://amzn.to/3Mro3JB', tag: 'Best Value', image: '/images/products/chunky-gold-statement-earrings.svg' },
      { name: 'Color-Block Knit Sweater', brand: 'Amazon', price: '$32', url: 'https://amzn.to/4anggFT', tag: 'Trending', image: '/images/products/color-block-knit-sweater.svg' },
      { name: 'Bright Orange Crossbody Bag', brand: 'Amazon', price: '$28', url: 'https://amzn.to/4tEIRhl', tag: 'Must Have', image: '/images/products/bright-orange-crossbody-bag.svg' },
    ],
  },
  {
    slug: 'winter-to-spring-transition-outfits-2026',
    title: 'Winter to Spring Transition Outfits 2026: What to Wear When the Weather Can\'t Decide',
    category: 'seasonal',
    description: 'Master the tricky winter-to-spring transition with layering strategies, versatile pieces, and outfit formulas that work in unpredictable weather. Your complete styling guide.',
    readTime: '11 min',
    date: '2026-02-19',
    tag: 'Hot',
    emoji: '\u{1F338}',
    image: '/images/guides/winter-to-spring-transition-outfits.svg',
    affiliateProducts: [
      { name: 'Lightweight Trench Coat', brand: 'The Drop', price: '$65', url: 'https://amzn.to/4rfVnSQ', tag: 'Editor Pick', image: '/images/products/lightweight-trench-coat.svg' },
      { name: 'Cotton-Cashmere Crewneck', brand: 'Amazon Essentials', price: '$32', url: 'https://amzn.to/3Mro3JB', tag: 'Best Value', image: '/images/products/cotton-cashmere-crewneck.svg' },
      { name: 'High-Waisted Wide-Leg Jeans', brand: 'Levi\'s', price: '$48', url: 'https://amzn.to/3ZCaw4S', tag: 'Must Have', image: '/images/products/high-waisted-wide-leg-jeans.svg' },
      { name: 'Quilted Vest', brand: 'Amazon', price: '$35', url: 'https://amzn.to/4anggFT', tag: 'Trending', image: '/images/products/quilted-vest.svg' },
      { name: 'Chelsea Ankle Boots', brand: 'Amazon', price: '$45', url: 'https://amzn.to/3OhrhzW', tag: 'Best Seller', image: '/images/products/chelsea-ankle-boots.svg' },
    ],
  },
  // ===== DATE NIGHT GUIDES =====
  {
    slug: 'valentines-day-outfit-ideas-2026',
    title: 'Valentine\'s Day Outfit Ideas 2026: Romantic Looks That Steal the Show',
    category: 'date-night',
    description: 'Find your perfect Valentine\'s Day outfit with romantic date night looks featuring reds, pinks, and sultry silhouettes. Shoppable picks from $22.',
    readTime: '11 min',
    date: '2026-02-21',
    tag: 'Hot',
    emoji: '❤️',
    image: '/images/guides/valentines-day-outfit-ideas-2026.svg',
    affiliateProducts: [
      { name: 'Red Satin Slip Dress', brand: 'Amazon', price: '$38', url: 'https://amzn.to/4tH7kT9', tag: 'Editor Pick', image: '/images/products/red-satin-slip-dress.svg' },
      { name: 'Strappy Heeled Sandals', brand: 'Amazon', price: '$45', url: 'https://amzn.to/3OhrhzW', tag: 'Date Night', image: '/images/products/strappy-heeled-sandals.svg' },
      { name: 'Heart Pendant Necklace', brand: 'Amazon', price: '$18', url: 'https://amzn.to/3Mro3JB', tag: 'Best Value', image: '/images/products/heart-pendant-necklace.svg' },
      { name: 'Velvet Clutch Bag', brand: 'Amazon', price: '$28', url: 'https://amzn.to/4anggFT', tag: 'Romantic Touch', image: '/images/products/velvet-clutch-bag.svg' },
    ],
  },
  {
    slug: 'summer-date-night-outfits-2026',
    title: 'Summer Date Night Outfits 2026: Warm Weather Looks That Turn Heads',
    category: 'date-night',
    description: 'Look stunning on summer date nights with breezy dresses, chic separates, and effortless evening styles. Budget-friendly picks all under $55.',
    readTime: '10 min',
    date: '2026-02-21',
    tag: 'Trending',
    emoji: '🌙',
    image: '/images/guides/summer-date-night-outfits-2026.svg',
    affiliateProducts: [
      { name: 'Floral Wrap Midi Dress', brand: 'Amazon', price: '$36', url: 'https://amzn.to/4rVjOFg', tag: 'Best Seller', image: '/images/products/floral-wrap-midi-dress.svg' },
      { name: 'Strappy Block Heel Sandals', brand: 'Amazon', price: '$42', url: 'https://amzn.to/3OhrhzW', tag: 'Most Comfortable', image: '/images/products/strappy-block-heel-sandals.svg' },
      { name: 'Layered Gold Necklace Set', brand: 'Amazon', price: '$16', url: 'https://amzn.to/3Mro3JB', tag: 'Summer Essential', image: '/images/products/layered-gold-necklace-set.svg' },
      { name: 'Straw Clutch Bag', brand: 'Amazon', price: '$24', url: 'https://amzn.to/4anggFT', tag: 'Trendy', image: '/images/products/straw-clutch-bag.svg' },
      { name: 'Linen Blend Blazer', brand: 'Amazon', price: '$48', url: 'https://amzn.to/4rfVnSQ', tag: 'Layering Pick', image: '/images/products/linen-blend-blazer.svg' },
    ],
  },
  {
    slug: 'casual-date-night-outfits-2026',
    title: 'Casual Date Night Outfits 2026: Cute Looks for Low-Key Dates',
    category: 'date-night',
    description: 'Movie night, pizza date, or bowling? These relaxed-but-cute casual date outfits prove you can look amazing without overdressing. All picks under $50.',
    readTime: '10 min',
    date: '2026-02-21',
    tag: 'Popular',
    emoji: '🍕',
    image: '/images/guides/casual-date-night-outfits-2026.svg',
    affiliateProducts: [
      { name: 'Ribbed Knit Bodysuit', brand: 'Amazon', price: '$22', url: 'https://amzn.to/4tH7kT9', tag: 'Wardrobe Staple', image: '/images/products/ribbed-knit-bodysuit.svg' },
      { name: 'High-Waist Straight Leg Jeans', brand: 'Amazon', price: '$38', url: 'https://amzn.to/3ZCaw4S', tag: 'Best Fit', image: '/images/products/high-waist-straight-leg-jeans.svg' },
      { name: 'Clean White Sneakers', brand: 'Amazon', price: '$42', url: 'https://amzn.to/40drBCf', tag: 'Most Versatile', image: '/images/products/clean-white-sneakers.svg' },
      { name: 'Mini Crossbody Bag', brand: 'Amazon', price: '$26', url: 'https://amzn.to/4anggFT', tag: 'Hands Free', image: '/images/products/mini-crossbody-bag.svg' },
    ],
  },
  {
    slug: 'anniversary-dinner-outfit-ideas-2026',
    title: 'Anniversary Dinner Outfit Ideas 2026: Elegant Looks for Your Special Night',
    category: 'date-night',
    description: 'Celebrate your anniversary in style with elegant dinner outfits that make the night unforgettable. From classic black to show-stopping color, all under $70.',
    readTime: '11 min',
    date: '2026-02-21',
    tag: 'New',
    emoji: '✨',
    image: '/images/guides/anniversary-dinner-outfit-ideas.svg',
    affiliateProducts: [
      { name: 'Satin Midi Dress (Black)', brand: 'Amazon', price: '$45', url: 'https://amzn.to/4tH7kT9', tag: 'Editor Pick', image: '/images/products/satin-midi-dress-black.svg' },
      { name: 'Pointed Toe Stiletto Heels', brand: 'Amazon', price: '$52', url: 'https://amzn.to/3OhrhzW', tag: 'Elegant Choice', image: '/images/products/pointed-toe-stiletto-heels.svg' },
      { name: 'Crystal Drop Earrings', brand: 'Amazon', price: '$18', url: 'https://amzn.to/3Mro3JB', tag: 'Best Value', image: '/images/products/crystal-drop-earrings.svg' },
      { name: 'Embellished Evening Clutch', brand: 'Amazon', price: '$32', url: 'https://amzn.to/4anggFT', tag: 'Statement Piece', image: '/images/products/embellished-evening-clutch.svg' },
      { name: 'Cashmere Wrap Shawl', brand: 'Amazon', price: '$35', url: 'https://amzn.to/4rfVnSQ', tag: 'Luxe Touch', image: '/images/products/cashmere-wrap-shawl.svg' },
    ],
  },
  {
    slug: 'trench-coat-outfits-styling-guide-2026',
    title: 'Trench Coat Outfits 2026: Your Ultimate Guide to Styling This Classic Staple',
    category: 'seasonal',
    description: 'Unlock the power of your trench coat! From casual chic to office glam, this guide shows you how to style the ultimate classic. Get easy outfit ideas for every occasion in 2026.',
    readTime: '10 min',
    date: '2026-02-21',
    tag: 'Pillar Guide',
    emoji: '🧥',
    image: '/images/guides/trench-coat-outfits-styling-guide.svg',
    affiliateProducts: [
      { name: 'Classic Tan Trench Coat', brand: 'Amazon', price: '$129', url: 'https://amzn.to/4rVjOFg', tag: 'Best Overall', image: '/images/products/classic-tan-trench-coat.svg' },
      { name: 'Waterproof Chelsea Boots', brand: 'Amazon', price: '$85', url: 'https://amzn.to/40drBCf', tag: 'Footwear Pick', image: '/images/products/waterproof-chelsea-boots.svg' },
      { name: 'Striped Breton Tee', brand: 'Amazon', price: '$35', url: 'https://amzn.to/3OrVpsf', tag: 'Staple Item', image: '/images/products/striped-breton-tee.svg' },
      { name: 'Structured Crossbody Bag', brand: 'Amazon', price: '$60', url: 'https://amzn.to/3Mro7cj', tag: 'Accessory Must-Have', image: '/images/products/structured-crossbody-bag.svg' },
    ],
  },
];

export function getGuideBySlug(slug: string) {
  return guides.find(g => g.slug === slug);
}

export function getGuidesByCategory(category: string) {
  if (category === 'all') return guides;
  return guides.filter(g => g.category === category);
}

/** Extract all products from all guides, deduplicated by name+brand */
export function getAllProducts(): (AffiliateProduct & { fromGuide: string; fromGuideSlug: string })[] {
  const seen = new Set<string>();
  const products: (AffiliateProduct & { fromGuide: string; fromGuideSlug: string })[] = [];
  for (const guide of guides) {
    if (!guide.affiliateProducts) continue;
    for (const p of guide.affiliateProducts) {
      const key = `${p.name}|${p.brand}`;
      if (seen.has(key)) continue;
      seen.add(key);
      products.push({ ...p, fromGuide: guide.title, fromGuideSlug: guide.slug });
    }
  }
  return products;
}

/** Get featured products based on tags like Editor Pick, Best Overall, etc. Deduplicates by image. */
export function getFeaturedProducts(count: number = 8): (AffiliateProduct & { fromGuide: string; fromGuideSlug: string })[] {
  const all = getAllProducts();
  const priorityTags = ['Editor Pick', 'Best Overall', 'Best Value', 'Best Seller', 'Trend Pick', 'Must Have', '#1 Must Have', 'Top Pick'];
  const featured = all.filter(p => p.tag && priorityTags.includes(p.tag));
  const rest = all.filter(p => !p.tag || !priorityTags.includes(p.tag));
  const sorted = [...featured, ...rest];
  // Deduplicate by image path to prevent visual duplicates
  const seenImages = new Set<string>();
  const unique: typeof sorted = [];
  for (const p of sorted) {
    const imgKey = p.image || p.name;
    if (seenImages.has(imgKey)) continue;
    seenImages.add(imgKey);
    unique.push(p);
  }
  return unique.slice(0, count);
}

/** Get products filtered by guide category */
export function getProductsByCategory(category: string, count: number = 8): (AffiliateProduct & { fromGuide: string; fromGuideSlug: string })[] {
  const seen = new Set<string>();
  const products: (AffiliateProduct & { fromGuide: string; fromGuideSlug: string })[] = [];
  const categoryGuides = category === 'all' ? guides : guides.filter(g => g.category === category);
  for (const guide of categoryGuides) {
    if (!guide.affiliateProducts) continue;
    for (const p of guide.affiliateProducts) {
      const key = `${p.name}|${p.brand}`;
      if (seen.has(key)) continue;
      seen.add(key);
      products.push({ ...p, fromGuide: guide.title, fromGuideSlug: guide.slug });
    }
  }
  return products.slice(0, count);
}

/** Category mapping for shop tabs */
export const shopCategories = [
  { slug: 'all', name: 'All' },
  { slug: 'workwear', name: 'Workwear' },
  { slug: 'casual', name: 'Casual' },
  { slug: 'date-night', name: 'Date Night' },
  { slug: 'seasonal', name: 'Seasonal' },
  { slug: 'budget', name: 'Budget Finds' },
];
